[package]
name = "PROYECTO_FINAL"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rand = "0.8.5"
sys-info = "0.9.0"
sysinfo = "0.23"
rayon = "1.5"